micronaut:
  application:
    name: testApi
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: jdbc:mariadb://localhost:3306/pokemon
    username: pokemon
    password: 123456
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update